# Generated by Django 5.0.4 on 2024-12-29 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('institution', models.CharField(max_length=200)),
                ('completion_date', models.DateField()),
                ('certificate_url', models.URLField(blank=True)),
                ('description', models.TextField(blank=True)),
                ('logo', models.ImageField(blank=True, upload_to='courses/')),
            ],
            options={
                'ordering': ['-completion_date'],
            },
        ),
        migrations.CreateModel(
            name='SocialMedia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('platform', models.CharField(max_length=50)),
                ('url', models.URLField()),
                ('icon', models.CharField(help_text='Font Awesome class name (e.g., fa-github)', max_length=50)),
            ],
        ),
    ]
