# Generated by Django 5.0.4 on 2024-12-31 07:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_course_socialmedia'),
    ]

    operations = [
        migrations.CreateModel(
            name='Achievement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('organization', models.CharField(max_length=200)),
                ('date', models.DateField()),
                ('description', models.TextField(blank=True)),
                ('position', models.CharField(blank=True, max_length=100)),
                ('certificate_url', models.URLField(blank=True)),
                ('logo', models.ImageField(blank=True, upload_to='achievements/')),
            ],
            options={
                'ordering': ['-date'],
            },
        ),
    ]
