# Generated by Django 5.0.4 on 2025-06-24 19:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_achievement'),
    ]

    operations = [
        migrations.AddField(
            model_name='skill',
            name='image',
            field=models.ImageField(default='skills/default.png', upload_to='skills/'),
        ),
    ]
